### ISSUE TITLE
Project compile issue.

### ISSUE THREAD

**Issue by motornyimaksym** [rsocket/rsocket-demo-android-java8#2]
I wasn't able to compile project because of issue with absent link to maven repository as described here: https://github.com/rsocket/rsocket-java

So I added it and everything goes ok. I created pull request with fix: https://github.com/rsocket/rsocket-demo-android-java8/pulls

Please review it and left comments if you disagree with something or you can merge it into your repo if you want.

**Comment by yschimke** [comment]
Sorry about this, anyway should be working in Android Studio even with older Android devices now.
